project:
  type: website

website:
  title: "Hello"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Skills.qmd
      - Projects.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

